use_frameworks!

target 'XHGAlertView_Example' do
    pod 'XHGAlertView', :path => '../', :subspecs =>['customizeMenuView']

  target 'XHGAlertView_Tests' do
    inherit! :search_paths

    
  end
end
